let createNewItem = '<section id="addNewItems">';
createNewItem += '           <h3>ADD NEW ITEMS</h3>';
createNewItem += '           <div>';
createNewItem += '               Item name: ';
createNewItem += '               <input type="text" id="newItemName" maxlength="15">';
createNewItem += '           </div>';
createNewItem += '          <div>';
createNewItem += '               Store or Market';
createNewItem += '               <select id="storeName">';
createNewItem += '                   <option value="Aldi">Aldi</option>';
createNewItem += '                   <option value="Coles">Coles</option>';
createNewItem += '                   <option value="Fruit_Market">Fruit Market</option>';
createNewItem += '                   <option value="other">other</option>';
createNewItem += '               </select>';
createNewItem += '           </div>';          
createNewItem += '           <div>';
createNewItem += '               Item Category';
createNewItem += '               <select id="categoryType">';
createNewItem += '                   <option value="produce">produce </option>';
createNewItem += '                   <option value="fresh">fresh </option>';
createNewItem += '                   <option value="canned">canned </option>';
createNewItem += '                   <option value="cleaning">cleaning </option>';
createNewItem += '               </select>';
createNewItem += '           </div>';
createNewItem += '           <div>';
createNewItem += '               Add to choices';
createNewItem += '               <button onclick="handlers.addNewItem()">Press</button>';
createNewItem += '           </div>';
createNewItem += '       </section>';