let createNewItem = '<section id="addNewItems">';
createNewItem += '           <h3><b>ADD NEW ITEMS</b></h3>';
createNewItem += '           <div class="form">';
createNewItem += '               <p>Item name</p> ';
createNewItem += '               <input type="text" id="newItemName" maxlength="15">';
createNewItem += '           </div>';
createNewItem += '          <div class="form">';
createNewItem += '               <p>Store or Market</p>';
createNewItem += '               <select id="storeName">';
createNewItem += '                   <option value="Aldi">Aldi</option>';
createNewItem += '                   <option value="Coles">Coles</option>';
createNewItem += '                   <option value="Fruit_Market">Fruit Market</option>';
createNewItem += '                   <option value="other">other</option>';
createNewItem += '               </select>';
createNewItem += '           </div>';          
createNewItem += '           <div class="form">';
createNewItem += '               <p>Item Category</p>';
createNewItem += '               <select id="categoryType">';
createNewItem += '                   <option value="produce">Produce </option>';
createNewItem += '                   <option value="fresh">Fresh </option>';
createNewItem += '                   <option value="canned">Canned </option>';
createNewItem += '                   <option value="cleaning">Cleaning </option>';
createNewItem += '               </select>';
createNewItem += '           </div>';
createNewItem += '           <div class="form">';
createNewItem += '               <p>Add to choices</p>';
createNewItem += '               <button onclick="handlers.addNewItem()" class="btn btn-success">Press</button>';
createNewItem += '           </div>';
createNewItem += '          <div class="form">';
createNewItem += '          <button onclick="handlers.removeMakeNewItems()" class="btn btn-success">Hide this section</button>';
createNewItem += '           </div>';
createNewItem += '       </section>';